# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
# and commit this file to your remote git repository to share the goodness with others.

# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
# and commit this file to your remote git repository to share the goodness with others.

image: gitpod/workspace-full

tasks:
  # - init: go get -v -t -d ./...
  - init: go get && go build ./... 

# vscode:
#   extensions:
#     - premparihar.gotestexplorer

# tasks:
#   - init: go get && go build ./... && go test ./...
#     command: go run .


